apiVersion: v1
kind: Pod
metadata:
  annotations:
    diamanti.com/endpoint0: '{"network":"default","perfTier":"high"}'
  name: busybox
spec:
  containers:
  - name: busybox-pod
    image: busybox
    command:
    - "/bin/sh"
    - "-c"
    - "sleep inf"
    volumeMounts:
      - name: snap-pvc
        mountPath: /data
  volumes:
  - name: snap-pvc
    persistentVolumeClaim:
      claimName: csi-pvc-filesystem-lcv  ## PVC 이름 지정
