apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-deploy
  labels:
    app: date
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date
  template:    
    metadata:
      labels:
        app: date
    spec:
      containers:
      - name: date-pod
        image: centos:7.5.1804
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 10; done"
        volumeMounts:
        - name: date
          mountPath: /data
      volumes:
      - name: date
        persistentVolumeClaim:
          claimName: snap02-pvc  ## PVC 이름 지정
