apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-snap-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "high"
  volumeMode: Filesystem
  volumeName: maria-snap-pv
