apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maria-snap-pvc
  namespace: prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 600Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: maria-snap-pv
