services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    hostname: gitlab
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://git.overmap.me'
          registry_external_url 'https://reg.overmap.me'

          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.naver.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "ID"
          gitlab_rails['smtp_password'] = "PASSWORD"
          gitlab_rails['smtp_domain'] = "smtp.naver.com"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
          gitlab_rails['gitlab_email_from'] = 'ID@naver.com'
          gitlab_rails['gitlab_email_reply_to'] = 'ID@naver.com'
          gitlab_rails['mattermost_host'] = "https://overmap.me"
          
          nginx['redirect_http_to_https'] = true
          nginx['redirect_http_to_https_port'] = 80

    network_mode: bridge
    ports:
      - 80:80
      - 443:443
      - 5005:5005
      - 5050:5050
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    restart: always
    extra_hosts:
      - "somehost:172.17.0.1"
