apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: date-snapshot
  namespace: default
spec:
  persistentVolumeClaim:
    claimName: date-pvc
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1
# ---
# apiVersion: gemini.fairwinds.com/v1beta1
# kind: SnapshotGroup
# metadata:
#   name: hackmd-postgresql
#   namespace: notepad
# spec:
#   persistentVolumeClaim:
#     claimName: data-hackmd-postgresql-0
#   schedule:
#     - every: "10 minutes"
#       keep: 3
#     - every: hour
#       keep: 1
