apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-red-01
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:    # You must add these two lines under spec-> template -> metadata
        diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
