# apiVersion: snapshot.storage.k8s.io/v1alpha1
# kind: VolumeSnapshot
# metadata:
#  name: csi-pvc-filesystem-snapshot
# spec:
#  snapshotClassName: csi-snapshotclass
#  source:
#    name: default-pvc
#    kind: PersistentVolumeClaim

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: default01-snapshot
spec:
  volumeSnapshotClassName: csi-cstor-snapshotclass
  source:
    persistentVolumeClaimName: default01-pvc
