apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web  #service가 바라보는 label이 아님. 주의.
spec:
  replicas: 10
  selector:
    matchLabels:
      app: web  
  template:
    metadata:
      labels:
        app: web  # Service가 바라보는 label 지정 
    spec:
      containers:
      - name: nginxhello
        image: nginxdemos/hello
