apiVersion: v1
kind: Service
metadata:
  name: nginxhello-svc
  # namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-hello
  sessionAffinity: None
  type: LoadBalancer