appVersion: v0.6.2
deprecated: true
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
keywords:
- cert-manager
- kube-lego
- letsencrypt
- tls
name: cert-manager
sources:
- https://github.com/jetstack/cert-manager
version: v0.6.7
