apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  flexVolume:
    driver: diamanti.com/nfs
    options:
      name: nfs-pv
      path: /
      server: 172.16.67.9
      type: nfs
  storageClassName: "high"

