apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
    - image: busybox
      name: busy-container1
      command: ["/bin/sleep","7d"]
      volumeMounts:
        - name: vol3
          mountPath: /data
  volumes:
    - name: vol3
      persistentVolumeClaim:
        claimName: nfs-pvc
