apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-02T16:56:56Z"
  generation: 1
  labels:
    app: tomcat
    chart: tomcat-2.1.3
    heritage: Tiller
    release: tomcat
  name: tomcat
  namespace: bizcube-test
  resourceVersion: "20086203"
  selfLink: /apis/extensions/v1beta1/namespaces/bizcube-test/deployments/tomcat
  uid: 485f9d00-661e-4168-af1d-071f001a411a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tomcat
      release: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tomcat
        chart: tomcat-2.1.3
        heritage: Tiller
        release: tomcat
    spec:
      containers:
      - env:
        - name: TOMCAT_USERNAME
          value: user
        - name: TOMCAT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: tomcat-password
              name: tomcat
        - name: TOMCAT_ALLOW_REMOTE_MANAGEMENT
          value: "0"
        image: docker.io/bitnami/tomcat:8.5.38
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: tomcat
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 51
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bitnami/tomcat
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: data
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-09-02T16:58:03Z"
    lastUpdateTime: "2020-09-02T16:58:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-09-02T16:56:56Z"
    lastUpdateTime: "2020-09-02T16:58:03Z"
    message: ReplicaSet "tomcat-749cf65d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
