apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
    chart: tomcat-6.3.15
    heritage: Tiller
    release: tomcat
  name: tomcat
  namespace: bizcube-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tomcat
      release: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'  # network 이름 지정
      labels:
        app: tomcat
        chart: tomcat-6.3.15
        heritage: Tiller
        release: tomcat
    spec:
      containers:
      - env:
        - name: TOMCAT_USERNAME
          value: user
        - name: TOMCAT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: tomcat-password
              name: tomcat
        - name: TOMCAT_ALLOW_REMOTE_MANAGEMENT
          value: "0"
        image: tomcat:8.5.57-jdk8-openjdk
        imagePullPolicy: IfNotPresent
        # livenessProbe:  # default page 생성 필요
        #   failureThreshold: 6
        #   httpGet:
        #     path: /
        #     port: http
        #     scheme: HTTP
        #   initialDelaySeconds: 120
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 5
        name: tomcat
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: http
        #     scheme: HTTP
        #   initialDelaySeconds: 30
        #   periodSeconds: 51
        #   successThreshold: 1
        #   timeoutSeconds: 3
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      # securityContext:  /usr/local/tomcat directory 권한 필요
      #   fsGroup: 1001
      #   runAsUser: 1001
      terminationGracePeriodSeconds: 30
