apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: gitlab
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab
  serviceName: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ee:latest
        name: gitlab
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: tls
          protocol: TCP
        - containerPort: 1022
          name: ssh
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 64Gi
          requests:
            cpu: "1"
            memory: 4Gi
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /-/readiness
            port: 80
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 180 # 초기 시작 3m 정도 많이 소요
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/liveness
            # path: /users/sign_in
            port: 80
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-config
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: gitlab-config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
#       storageClassName: high2m
      volumeMode: Filesystem
  - metadata:
      name: gitlab-logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: gitlab-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: high2m
      volumeMode: Filesystem
