apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  # sessionAffinity: None
  type: LoadBalancer
  # loadBalancerIP: 172.17.19.240