apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.snapshotVolumeConfig.name}}
{{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
{{- end }}
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: {{ .Values.snapshotVolumeConfig.snapshotName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.snapshotVolumeConfig.size }}
  storageClassName: {{ .Values.snapshotVolumeConfig.storageClass }}

