apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2020-10-30T04:41:12Z"
  generation: 5
  labels:
    app: kube-prometheus-stack-alertmanager
    chart: kube-prometheus-stack-10.3.2
    heritage: Tiller
    release: prometheus
  name: alertmanager
  namespace: monitoring
  # ownerReferences:
  # - apiVersion: monitoring.coreos.com/v1
  #   blockOwnerDeletion: true
  #   controller: true
  #   kind: Alertmanager
  #   name: prometheus-kube-prometheus-alertmanager
  #   uid: e17d3ead-5fa2-4cb1-8633-5cd730eec4e3
  resourceVersion: "7853190"
  selfLink: /apis/apps/v1/namespaces/monitoring/statefulsets/alertmanager-prometheus-kube-prometheus-alertmanager
  uid: a11a815a-bcb6-49c2-82ef-8a59d5bb331a
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      alertmanager: prometheus-kube-prometheus-alertmanager
      app: alertmanager
  serviceName: alertmanager-operated
  template:
    metadata:
      labels:
        alertmanager: prometheus-kube-prometheus-alertmanager
        app: alertmanager
      annotations:
        diamanti.com/endpoint0: '{"endpointId":"alertmanager","perfTier":"high"}'
    spec:
      containers:
      - args:
        - --config.file=/etc/alertmanager/config/alertmanager.yaml
        - --storage.path=/alertmanager
        - --data.retention=120h
        - --cluster.listen-address=
        - --web.listen-address=:9093
        - --web.external-url=http://prometheus-kube-prometheus-alertmanager.monitoring:9093
        - --web.route-prefix=/
        - --cluster.peer=alertmanager-prometheus-kube-prometheus-alertmanager-0.alertmanager-operated:9094
        - --cluster.reconnect-timeout=5m
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: quay.io/prometheus/alertmanager:v0.21.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        name: alertmanager
        ports:
        - containerPort: 9093
          name: web
          protocol: TCP
        - containerPort: 9094
          name: mesh-tcp
          protocol: TCP
        - containerPort: 9094
          name: mesh-udp
          protocol: UDP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          requests:
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
        - mountPath: /alertmanager
          name: alertmanager-prometheus-kube-prometheus-alertmanager-db
      - args:
        - -webhook-url=http://127.0.0.1:9093/-/reload
        - -volume-dir=/etc/alertmanager/config
        image: docker.io/jimmidyson/configmap-reload:v0.4.0
        imagePullPolicy: IfNotPresent
        name: config-reloader
        resources:
          limits:
            cpu: 100m
            memory: 25Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /etc/alertmanager/config
          name: config-volume
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: prometheus-kube-prometheus-alertmanager
      serviceAccountName: prometheus-kube-prometheus-alertmanager
      terminationGracePeriodSeconds: 120
      volumes:
      - name: config-volume
        secret:
          defaultMode: 420
          secretName: alertmanager-prometheus-kube-prometheus-alertmanager
      - emptyDir: {}
        name: alertmanager-prometheus-kube-prometheus-alertmanager-db
  updateStrategy:
    type: RollingUpdate
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: alertmanager-prometheus-kube-prometheus-alertmanager-54d4f5b784
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updateRevision: alertmanager-prometheus-kube-prometheus-alertmanager-54d4f5b784
  updatedReplicas: 1
