apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  resourceVersion: "3544635"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
