[logging]
level="info"

[httpserver.default]
address=":8000"

[zookeeper]
servers=[ "felice-zoo:2181" ]
timeout=6
root-path="/felice/burrow"

### cluster : ccs ###
[client-profile.ccs]
kafka-version="2.6.0"
sasl="ccs"

[sasl.ccs]
username="admin"
password="admin-secret"
mechanism="SCRAM-SHA-512"

[cluster.ccs]
class-name="kafka"
servers=[ "172.17.19.49:9093", "172.17.19.60:9093", "172.17.19.63:9093" ]
client-profile="ccs"
topic-refresh=60
offset-refresh=5

[consumer.ccs]
class-name="kafka"
cluster="ccs"
servers=[ "172.17.19.49:9093", "172.17.19.60:9093", "172.17.19.63:9093" ]
client-profile="ccs"

### cluster : maas ###
[cluster.maas]
class-name="kafka"
servers=[ "172.17.19.4:9092", "172.17.19.5:9092", "172.17.19.9:9092" ]
topic-refresh=60
offset-refresh=5

[consumer.maas]
class-name="kafka"
cluster="maas"
servers=[ "172.17.19.4:9092", "172.17.19.5:9092", "172.17.19.9:9092" ]
