version: '3.8'

services:
  felice-mon:
    #image: prom/prometheus:latest
    image: 172.17.19.54:4567/kafka_controller/prometheus-docker:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - prom-data:/prometheus
      - ./rules:/opt/felice/rules:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - 'zoo1 kafka1:172.17.19.49'
      - 'zoo2 kafka2:172.17.19.60'
      - 'zoo3 kafka3:172.17.19.63'
    environment:
      PROMETHEUS_STORAGE_TSDB_RETENTION_TIME: 60d


  felice-board:
    #image: grafana/grafana:latest
    image: 172.17.19.54:4567/kafka_controller/grafana-docker:latest
    depends_on:
      - felice-mon
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana


  felice-back:
    image: 172.17.19.54:4567/kafka_controller/api_server:develop-1.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/monitor/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m
    restart: unless-stopped
    ports:
      - 8989:8989
      - 7000:7000
    volumes:
      - ./felice-data:/felice-api/data
      - ./rules:/felice-api/prom-rules
      - ./logs:/felice-api/logs


  felice-front:
    image: 172.17.19.54:4567/kafka_controller/client:1.0.0
    depends_on:
      - felice-back
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/monitor/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped
    ports:
      - 80:80


  felice-zoo:
    image: 172.17.19.54:4567/kafka_controller/zookeeper-docker:3.6.2
    healthcheck:
      test: ["CMD", "bin/zkCli.sh", "version"]
      interval: 2m
      timeout: 30s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped
    volumes:
      - zoo-data:/data
      - ./zoo.cfg:/conf/zoo.cfg


  felice-lag:
    image: 172.17.19.54:4567/kafka_controller/burrow-docker:latest
    depends_on:
      - felice-zoo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/burrow/admin"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./burrow.toml:/etc/burrow/burrow.toml
    environment:
      WAIT_HOST: felice-zoo:2181
      WAIT_BEFORE_HOSTS: 3


volumes:
  prom-data:
  grafana-data:
  zoo-data:


