apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: felice-back-pvc
  namespace: kafka
spec:
  accessModes:
  - ReadWriteOnce  ## block accessmode 지정 
  resources:
    requests:
      # storage: 10Gi
      storage: 10Gi  # 노드 Disk 용량을 넘으면 할당이 안 됨
  storageClassName: "high"  ## SC 지정
