global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'felice-monitor'

rule_files:
  - /opt/felice/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - felice-back:8989
    - api_version: v2
    - path_prefix: /api/v2

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label  to any timeseries scraped from this config.
  #### INTERNAL PROMETHEUS ####
  - job_name: 'felice-mon'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['felice-mon:9090']

  #### FELICE BACKEND ####
  - job_name: 'felice-back'
    scrape_interval: 5s
    metrics_path: /monitor/metrics
    static_configs:
      - targets: ['felice-back:7000']

  #### FELICE FRONT ####


  #### BURROW ####
  - job_name: 'consumer-lag'
    scrape_interval: 5s
    static_configs:
      - targets: ['felice-lag:8000']
        labels:
          instance: 'burrow'

  #### INTERNAL ZooKeeper for burrow ####
  - job_name: 'felice-zoo'
    scrape_interval: 5s
    static_configs:
      - targets: ['felice-zoo:7000']

  #### CLUSTER 1 : ccs ####
  ## ZooKeeper
  - job_name: 'ccs-zookeeper'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.49:7000']
        labels:
          instance: 1
      - targets: ['172.17.19.60:7000']
        labels:
          instance: 2
      - targets: ['172.17.19.63:7000']
        labels:
          instance: 3

  ## Zookeeper_node
  - job_name: 'ccs-zookeeper_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.49:9200']
        labels:
          instance: 1
      - targets: ['172.17.19.60:9200']
        labels:
          instance: 2
      - targets: ['172.17.19.63:9200']
        labels:
          instance: 3

  ## Kafka
  - job_name: 'ccs-kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.49:7100']
        labels:
          instance: 1001
      - targets: ['172.17.19.60:7100']
        labels:
          instance: 1002
      - targets: ['172.17.19.63:7100']
        labels:
          instance: 1003

  ## Kafka_node
  - job_name: 'ccs-kafka_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.49:9200']
        labels:
          instance: 1001
      - targets: ['172.17.19.60:9200']
        labels:
          instance: 1002
      - targets: ['172.17.19.63:9200']
        labels:
          instance: 1003

  ## Schema-Registry      
  - job_name: 'ccs-schema_registry'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.49:7200']
        labels:
          instance: 1

  ## Schema-Registry_node
  - job_name: 'ccs-schema_registry_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka1:9200']
        labels:
          instance: 1

  #### CLUSTER 2 : maas ####
  ## Kafka
  - job_name: 'maas-kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.4:7100']
        labels:
          instance: 1
      - targets: ['172.17.19.5:7100']
        labels:
          instance: 2
      - targets: ['172.17.19.9:7100']
        labels:
          instance: 3

  ## Kafka_node
  - job_name: 'maas-kafka_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.19.4:9200']
        labels:
          instance: 1
      - targets: ['172.17.19.5:9200']
        labels:
          instance: 2
      - targets: ['172.17.19.9:9200']
        labels:
          instance: 3

