apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
      annotations:
        diamanti.com/endpoint0: '{"endpointId":"grafana","perfTier":"high"}'    
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "16Gi"
            cpu: "4"
          requests: 
            memory: "4Gi"
            cpu: "1"
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          # - mountPath: /etc/grafana/provisioning/datasources
          #   name: grafana-datasources
          #   readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-storage  ## PVC 이름 지정
        # - name: grafana-datasources
        #   configMap:
        #       defaultMode: 420
        #       name: grafana-datasources
