name: "Verify Velero CRDs on k8s 1.16.9"
on: [pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: engineerd/setup-kind@v0.5.0
      with:
          image: "kindest/node:v1.16.9"
    - name: Testing
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
        kubectl version
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        make local
        ./_output/bin/linux/amd64/velero install --crds-only --dry-run -oyaml | kubectl apply -f -
