apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    diamanti.com/app: alertmanager
    diamanti.com/cluster-service: "true"
    version: alertmanager-v0.1
  name: alertmanager
  namespace: diamanti-system
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      diamanti.com/app: alertmanager
  serviceName: alertmanager
  template:
    metadata:
      annotations:
        diamanti.com/endpoint: none
      labels:
        diamanti.com/app: alertmanager
        diamanti.com/cluster-service: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - adzdia03  # 왜 그럴까?
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: diamanti.com/app
                operator: In
                values:
                - alertmanager
            topologyKey: kubernetes.io/hostname
      containers:
      - command:
        - sh
        - -c
        - cd /data; /bin/alertmanager --config.file=/etc/prometheus/config/alertmanager.yml
        image: quay.io/prometheus/alertmanager:v0.16.1
        imagePullPolicy: IfNotPresent
        name: alertmanager
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config-volume
          readOnly: true
        - mountPath: /data
          name: alertmanager-persistent-storage
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: monitoring-system
      serviceAccountName: monitoring-system
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/diamanti/prometheus
          type: ""
        name: config-volume
      - hostPath:
          path: /var/lib/diamanti/stats
          type: ""
        name: alertmanager-persistent-storage
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
