global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 5s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - prometheus-svc:9093
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus/config/alert.rules
scrape_configs:
- job_name: collectd-exporter
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - adzdia01:9103
    - adzdia02:9103
    - adzdia03:9103
    - adzdia04:9103
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):.*
    target_label: source
    replacement: ${1}
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: scrape_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: collectd_interface_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: collectd_load(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: collectd_disk_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: collectd_ipmi(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: process_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: http_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: go_(.*)
    replacement: $1
    action: drop
- job_name: node-exporter
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - adzdia01:9111
    - adzdia02:9111
    - adzdia03:9111
    - adzdia04:9111
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):.*
    target_label: source
    replacement: ${1}
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: promhttp_metric_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: node_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: process_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: http_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: go_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_board_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_dec_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_ecc_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_enc_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_low_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_mem(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_pcie_replay(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_power_violation(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_reliability_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_retired_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_sm_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_sync_(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_thermal_violation(.*)
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: dcgm_xid_errors(.*)
    replacement: $1
    action: drop
- job_name: federate
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{job="node-exporter"}'
    - '{job="collectd-exporter"}'
    - '{job="mysql-exporter"}'
    - '{__name__=~"job:.*"}'
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  static_configs:
  - targets: []
- job_name: mysql-exporter
  scrape_interval: 10s
  static_configs:
  - targets:
    - 10.82.1.124:9104
    - 10.82.1.125:9104
    - 10.82.1.126:9104
    labels:
      group: 'ac1-web-db'
  - targets:
    - 10.82.1.50:9104
    - 10.82.1.51:9104
    - 10.82.1.52:9104
    labels:
      group: 'ac1-mail-db'
  - targets:
    - 10.82.1.114:9104
    - 10.82.1.115:9104
    - 10.82.1.116:9104
    labels:
      group: 'ac2-web-db'
  - targets:
    - 10.82.1.117:9104
    - 10.82.1.118:9104
    - 10.82.1.119:9104
    labels:
      group: 'ac2-mail-db'
  - targets:
    - 10.82.1.90:9104
    - 10.82.1.91:9104
    - 10.82.1.92:9104
    labels:
      group: 'ac3-web-db'
  - targets:
    - 10.82.1.87:9104
    - 10.82.1.88:9104
    - 10.82.1.89:9104
    labels:
      group: 'ac3-mail-db'
  - targets:
    - 10.82.1.155:9104
    - 10.82.1.156:9104
    - 10.82.1.157:9104
    labels:
      group: 'ac4-web-db'
  - targets:
    - 10.82.1.152:9104
    - 10.82.1.153:9104
    - 10.82.1.154:9104
    labels:
      group: 'ac4-mail-db'
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):.*
    target_label: source
    replacement: ${1}
    action: replace
  #metric_relabel_configs:
  #- source_labels: [__name__]
  #  separator: ;
  #  regex: mysql_global_status_(.*)
  #  replacement: $1
  #  action: drop
