apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: deploy-image-taskrun
spec:
  serviceAccountName: tutorial-service
  taskRef:
    name: deploy-app
  resources:
    inputs:
    - name: source-repo
      resourceRef:
        name: git-app-repo
  params:
  - name: path
    value: "/tomcat-board.yml"
