apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-pvc-mirror
  labels:
    app: date-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-mirror
  template:    
    metadata:
      labels:
        app: date-mirror
    spec:
      containers:
      - name: date-pod
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 10; done"
        volumeMounts:  # Volume을 POD에 어디에 마운트 할 것인지
        - name: date-vol  # Volume 이름
          mountPath: /data  # Mount 이름 
  volumeClaimTemplates:
    - metadata:
        name: date-vol
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: high2m
        volumeMode: Filesystem
          