apiVersion: apps/v1
kind: Deployment
metadata:
  name: date-pvc-mirror
  labels:
    app: date-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: date-mirror
  template:    
    metadata:
      labels:
        app: date-mirror
    spec:
      containers:
      - name: date-pod
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do date >> /data/pod-out.txt; cd /data; sync; sync; sleep 10; done"
        volumeMounts:
        - name: date-vol
          mountPath: /data
      volumes:
      - name: date-vol
        persistentVolumeClaim:
          claimName: perf-pvc  ## PVC 이름 지정
