apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perf-large-pvc
  namespace: test 
spec:
  accessModes:
  - ReadWriteOnce  ## block accessmode 지정 
  resources:
    requests:
      storage: 10Gi
      # storage: 5Ti  # 노드 Disk 용량을 넘으면 할당이 안 됨
  storageClassName: "high2m"  ## SC 지정
