apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cent-tools
  name: cent-tools
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cent-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cent-tools
    spec:
      containers:
      - image: centos/tools
        imagePullPolicy: Always
        name: tools
        command:
        - /bin/sh
        - -c
        - "sleep inf"
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30