apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-09-19T19:39:40Z"
  generation: 1
  labels:
    app: cent-tools
  name: cent-tools
  namespace: bizcube-test
  resourceVersion: "7433782"
  selfLink: /apis/apps/v1/namespaces/bizcube-test/deployments/cent-tools
  uid: 271020cd-1866-4351-b347-cb6a75aea48f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cent-tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cent-tools
    spec:
      containers:
      - image: centos/tools
        imagePullPolicy: Always
        name: tools
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-09-19T19:39:40Z"
    lastUpdateTime: "2020-09-19T19:41:18Z"
    message: ReplicaSet "cent-tools-9c44ff88b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-09-19T19:41:47Z"
    lastUpdateTime: "2020-09-19T19:41:47Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
