apiVersion: v1
kind: Pod
metadata:
  annotations:
    diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'
  name: busybox
spec:
  containers:
  - name: busybox-pod
    image: busybox:0.1
    command:
    - "/bin/sh"
    - "-c"
    - "sleep inf"
