apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elastic-system
data:
  elasticsearch.yml: |
    cluster:
      name: elasticsearch
    discovery:
      seed_providers: file
    network:
      host: 0.0.0.0
      publish_host: ${POD_IP}
    node:
      data: true
      ingest: true
      master: true
      name: ${POD_NAME}
      remote_cluster_client: false
      store:
        allow_mmap: false
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/logs
      repo: /usr/share/elasticsearch/backup
    bootstrap:
      memory_lock: true
    http:
      port: 19204
    xpack:
      license:
        upload:
          types:
          - trial
          - enterprise
      security:
        authc:
          realms:
            file:
              file1:
                order: -100
            native:
              native1:
                order: -99
          reserved_realm:
            enabled: "false"
        enabled: "true"
        http:
          ssl:
            certificate: /usr/share/elasticsearch/config/http-certs/tls.crt
            certificate_authorities: /usr/share/elasticsearch/config/http-certs/ca.crt
            enabled: true
            key: /usr/share/elasticsearch/config/http-certs/tls.key
        transport:
          ssl:
            certificate: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.crt
            certificate_authorities:
            - /usr/share/elasticsearch/config/transport-certs/ca.crt
            - /usr/share/elasticsearch/config/transport-remote-certs/ca.crt
            enabled: "true"
            key: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.key
            verification_mode: certificate