apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: prometheus
  labels:
    app: kube-prometheus-stack-node-exporter
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-14.3.0
    heritage: Helm
    release: prometheus
  name: diamanti-prometheus-collectd
  namespace: prometheus
spec:
  endpoints:
  - honorLabels: true
    port: cadvisor
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - diamanti-system
  selector:
    matchLabels:
      name: collectd-svc  # label for service
