kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc
  namespace: default
spec:
  storageClassName: high
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G