{
 "title": "Diamanti Node Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{job=\"collectd-svc\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(node_load1{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "max(node_load5{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "max(node_load15{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Usage Per Core",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{job=\"collectd-svc\", mode!=\"idle\", instance=\"$instance\"}[5m]))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Utilizaion",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max (sum by (cpu) (irate(node_cpu_seconds_total{job=\"collectd-svc\", mode!=\"idle\", instance=\"$instance\"}[2m])) ) * 100\n",
     "legendFormat": "{{ cpu }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(sum by (cpu) (irate(node_cpu_seconds_total{job=\"collectd-svc\", mode!=\"idle\", instance=\"$instance\"}[2m]))) * 100\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_memory_MemTotal_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n  - node_memory_MemFree_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n  - node_memory_Buffers_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n  - node_memory_Cached_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "max(node_memory_Buffers_bytes{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "max(node_memory_Cached_bytes{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "max(node_memory_MemFree_bytes{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_memory_MemTotal_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n    - node_memory_MemFree_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n    - node_memory_Buffers_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n    - node_memory_Cached_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n    )\n    / node_memory_MemTotal_bytes{job=\"collectd-svc\", instance=\"$instance\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=\"collectd-svc\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=\"collectd-svc\", instance=\"$instance\", device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  node_filesystem_files{job=\"collectd-svc\", instance=\"$instance\"}\n  - node_filesystem_files_free{job=\"collectd-svc\", instance=\"$instance\"}\n)\n",
     "legendFormat": "inodes used"
    },
    {
     "expr": "max(node_filesystem_files_free{job=\"collectd-svc\", instance=\"$instance\"})",
     "legendFormat": "inodes free"
    }
   ]
  },
  {
   "title": "Inodes Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(\n  (\n    (\n      node_filesystem_files{job=\"collectd-svc\", instance=\"$instance\"}\n    - node_filesystem_files_free{job=\"collectd-svc\", instance=\"$instance\"}\n    )\n    / node_filesystem_files{job=\"collectd-svc\", instance=\"$instance\"}\n  ) * 100)\n"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=\"collectd-svc\", instance=\"$instance\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=\"collectd-svc\", instance=\"$instance\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total{job=\"collectd-svc\",  instance=\"$instance\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  }
 ]
}
{
 "title": "Diamanti Pod Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(exported_namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(diamanti_container_cpu_load_average_10s{exported_namespace=\"$namespace\"},pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{exported_namespace=~\"$namespace\", pod_name=~\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(diamanti_container_memory_usage_bytes{exported_namespace=\"$namespace\",pod_name=~\"$pod\"}) by (exported_namespace,pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(diamanti_container_cpu_load_average_10s{exported_namespace=\"$namespace\",pod_name=~\"$pod\"}) by (exported_namespace,pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Diamanti Volume Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server",
    "query": "label_values(collectd_disk_disk_ops_write_total,exported_instance)"
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": "label_values(collectd_disk_disk_ops_write_total{exported_instance=\"$instance\"},disk)"
   }
  ]
 },
 "panels": [
  {
   "title": "Write IOPS Per NVME Partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "collectd_disk_disk_ops_write_total{disk=~\"$partition\",exported_instance=~\"$instance\"}",
     "legendFormat": "{{exported_instance}}: {{disk}}"
    }
   ]
  },
  {
   "title": "Read IOPS Per NVME Partition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "collectd_disk_disk_ops_read_total{disk=~\"$partition\",exported_instance=~\"$instance\"}",
     "legendFormat": "{{exported_instance}}: {{disk}}"
    }
   ]
  },
  {
   "title": "Space Used per Claim",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "collectd_df_df_complex{exported_instance=~\"$instance\",type=\"used\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}
{
 "title": "Diamanti Network Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server",
    "query": "label_values(exported_instance)"
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": "label_values(collectd_interface_if_packets_rx_total{exported_instance=\"$instance\"},interface)"
   }
  ]
 },
 "panels": [
  {
   "title": "VF RX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(collectd_interface_if_packets_rx_total{exported_instance=~\"$instance\",interface=~\"$interface\"}) by (exported_instance,interface)",
     "legendFormat": "{{exported_instance}}: {{interface}}"
    }
   ]
  },
  {
   "title": "VF TX",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(collectd_interface_if_packets_tx_total{exported_instance=~\"$instance\",interface=~\"$interface\"}) by (exported_instance,interface)",
     "legendFormat": "{{exported_instance}}: {{interface}}"
    }
   ]
  },
  {
   "title": "Endpoint TX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(diamanti_endpoint_bytes_tx) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Endpoint RX",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(diamanti_endpoint_bytes_rx) by (exported_endpoint)",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  }
 ]
}
{
 "title": "Diamanti StatefulSets Stats",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\"}, namespace)"
   },
   {
    "name": "statefulset",
    "label": "Name",
    "query": "label_values(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", namespace=\"$namespace\"}, statefulset)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{exported_namespace=~\"$namespace\", pod_name=~\"$statefulset.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{exported_namespace=~\"$namespace\", pod_name=~\"$statefulset.*\"}) / 1024^3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{exported_namespace=~\"$namespace\", pod_name=~\"$statefulset.*\"}[3m])) + sum(rate(container_network_receive_bytes_total{exported_namespace=~\"$namespace\",pod_name=~\"$statefulset.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Desired Replicas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{namespace=~\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas of current version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Observed Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_status_observed_generation{job=\"kube-state-metrics\",  namespace=\"$namespace\", statefulset=\"$statefulset\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Metadata Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kube_statefulset_metadata_generation{job=\"kube-state-metrics\", statefulset=\"$statefulset\", namespace=\"$namespace\"}) without (instance, pod)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kube_statefulset_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas specified"
    },
    {
     "expr": "max(kube_statefulset_status_replicas{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas created"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "ready"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_current{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "replicas of current version"
    },
    {
     "expr": "min(kube_statefulset_status_replicas_updated{job=\"kube-state-metrics\", statefulset=\"$statefulset\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "updated"
    }
   ]
  }
 ]
}