apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"gitlab","namespace":"gitlab"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gitlab"}},"serviceName":"gitlab","template":{"metadata":{"annotations":{"diamanti.com/endpoint0":"{\"network\":\"blue\",\"perfTier\":\"high\"}"},"labels":{"app":"gitlab"}},"spec":{"containers":[{"env":[{"name":"hostname","value":"spkr.gitlab.io"}],"image":"gitlab/gitlab-ce:latest","name":"gitlab","ports":[{"containerPort":80,"name":"web"},{"containerPort":443,"name":"tls"},{"containerPort":22,"name":"ssh"}],"resources":{"limits":{"cpu":"4","memory":"64Gi"},"requests":{"cpu":"1","memory":"16Gi"}},"volumeMounts":[{"mountPath":"/etc/gitlab","name":"gitlab-config"},{"mountPath":"/var/log/gitlab","name":"gitlab-logs"},{"mountPath":"/var/opt/gitlab","name":"gitlab-data"}]}]}},"volumeClaimTemplates":[{"metadata":{"name":"gitlab-config"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Gi"}},"storageClassName":"high2m"}},{"metadata":{"name":"gitlab-logs"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"high2m"}},{"metadata":{"name":"gitlab-data"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"high2m"}}]}}
  creationTimestamp: "2020-11-09T01:21:11Z"
  generation: 1
  name: gitlab
  namespace: gitlab
  resourceVersion: "1378992"
  selfLink: /apis/apps/v1/namespaces/gitlab/statefulsets/gitlab
  uid: 89c0bc8a-ed4e-4f19-bd6b-c9103316f62e
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab
  serviceName: gitlab
  template:
    metadata:
      annotations:
        diamanti.com/endpoint0: '{"network":"green","perfTier":"high"}'
      creationTimestamp: null
      labels:
        app: gitlab
    spec:
      containers:
      - env:
        - name: hostname
          value: douzone.gitlab.io
        image: gitlab/gitlab-ee:latest
        # imagePullPolicy: Always
        name: gitlab
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: tls
          protocol: TCP
        - containerPort: 1022
          name: ssh
          protocol: TCP
        resources:
          limits:
            cpu: "4"
            memory: 64Gi
          requests:
            cpu: "1"
            memory: 4Gi
        readinessProbe:
          failureThreshold: 5
          httpGet:
            # path: /-/readiness
            path: /
            port: 80
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 2
          initialDelaySeconds: 180 # 초기 시작 5m 정도 많이 소요
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     # path: /-/liveness
        #     path: /-/readiness
        #     port: 80
        #     scheme: HTTP
        #   initialDelaySeconds: 20
        #   periodSeconds: 60
        #   successThreshold: 1
        #   timeoutSeconds: 30
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/gitlab
          name: gitlab-config
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /var/opt/gitlab
          name: gitlab-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: gitlab-config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: high2m
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: gitlab-logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: high2m
      volumeMode: Filesystem
    status:
      phase: Pending
  - metadata:
      creationTimestamp: null
      name: gitlab-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: high2m
      volumeMode: Filesystem
    status:
      phase: Pending
